### ISSUE TITLE
Dose the network infer with different trained-models on different scene?

### ISSUE THREAD

**Issue by lizhuo1991** [nqanh/pose_relocalization#1]

**Comment by nqanh** [comment]
You will need each trained model for each scene.

**Comment by lizhuo1991** [comment]
Firstly, thanks for your response. It means, for each scene, I will need to train network to obtain each model. Then I will employ each model to predict pose for each scene respectively. Do I understand correctly?

**Comment by nqanh** [comment]
Yes, that's right!

**Comment by lizhuo1991** [comment]
Thanks again, and have a good day.
